accounts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('my_page/<int:pk>/', views.my_page, name='my_page')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

boards/urls.py
from django.urls import path
from .views import *

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', main_page, name='main'),
    path('board/', board_list, name='board_list'),
    path('board/post/', board_post, name='board_post'),
    path('board/<int:pk>/', board_detail, name='board_detail'),
    path('board/update/<int:pk>/', board_update, name='board_update'),
    path('board/delete/<int:pk>/', board_delete, name='board_delete'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

petthon/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('boards.urls')),
]

accounts/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models


class MyAccountManager(BaseUserManager):
    # 일반 user 생성, username 이 userID를 의미함
    def create_user(self, username, email, profile, password=None):
        if not username:
            raise ValueError("Users must have an userID.")
        if not email:
            raise ValueError("Users must have an email.")
        user = self.model(
            username=username,
            email=self.normalize_email(email),
            profile=profile
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    # 관리자 User 생성
    def create_superuser(self, username, email, profile, password, **extra_fields):
        user = self.create_user(
            username=username,
            email=email,
            profile=profile,
            password=password
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.is_active = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    username = models.CharField(max_length=30, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    profile = models.FileField(upload_to='profile/%Y/%m/%d', default="profile/default.png")
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    object = MyAccountManager()  # 헬퍼 클래스 사용

    USERNAME_FIELD = 'username'  # 로그인 ID로 사용할 필드
    REQUIRED_FIELDS = ['email', 'profile']  # 필수 작성 필드

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_lable):
        return True

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from .models import User
from django.contrib.auth.forms import PasswordResetForm as BasePasswordResetForm


# This is Form Login Form

class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email']

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

accounts/views.py
from django.contrib.auth import authenticate, login

from .models import *
from boards.models import *
from .forms import UserForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

def signup(request):
    if request.method == "POST":
        print(request.POST)
        form = UserForm(request.POST)
        print(form.is_valid())
        if form.is_valid():
            account = form.save(commit=False)
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, email=email, password=raw_password)
            if user is not None:
                login(request, user)
            account.save()
            return redirect('accounts:login')
    else:
        form = UserForm()
    return render(request, 'accounts/signup.html', {'form': form})

@login_required
def my_page(request, pk):
    user = get_object_or_404(User, pk=pk)
    user_posts = user.post.all()

    count = user_posts.count()

    context = {
        'user': user,
        'user_posts' : user_posts,
        'count' : count
    }
    return render(request, "accounts/mypage.html", context)

accounts/templates/accounts/login.html
{% extends 'nav_bar.html' %}
{% block content %}
{% load static %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <div class = "container">
        <!--로고 부분-->
        <div id="logo"> 
            <img src="{% static 'img/tipton.png' %}" alt="로고 사진">
        </div>
        <!--로고 부분 끝-->

        <!--★★입력창 form 부분-->
        <form  name="login-form" action="{% url 'accounts:login' %}" method="post" class ="user">
            {% csrf_token %}
            <input type="text" placeholder="ID" class="inputStyle" name="username" value="" required> <!--★★아이디 입력 받는 부분-->
            <input type="password" name="password" placeholder="PW" class="inputStyle" required> <!--★★비밀번호 입력 받는 부분-->
            <div class = "buttons"> <!--로그인/회원가입 버튼들 -->
                <button type="submit" class="buttonStyle">Log in</button><br> <!--로그인 버튼-->
                <a href="{% url 'accounts:signup' %}"><!--★★회원가입 페이지로 url 연결-->
                    <button type="button" class ="buttonStyle">Sign up</button> <!--회원가입 버튼-->
                </a>
            </div>
        </form>
        <!--입력창 form 끝-->
    </div>
{% endblock %}

accounts/templates/accounts/mypage.html
{% extends 'nav_bar.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/mypage.css' %}">
<div class="container">
    <!-- 프로필 이미지 부분 => 사람 아이콘 알죠? -->
    <div class="user_logo">
        <img src="{% static 'img/image 56.png' %}" alt="">
    </div>
    <div class="profile">
        <div class="profile_name">
            <p>{{ user.username }}</p>
        </div>
        <div class="profile_post">
            <p>작성글 <br>{{ count }} </p>
        </div>
    </div>

    <img src="{% static 'img/Vector 5.png' %}" alt="">

    <div class="post">
        <p>내가 작성한 게시글</p>
    </div>
    <img class="line" src="{% static 'img/Line 5.png' %}" alt="">
    {% for board in user_posts %}
    <div class="post_1">
        <a href="{% url 'board_detail' pk=board.pk %}"><p>{{ board.title }}</p></a>
        <h6>{{ board.created_date }}</h6>
    </div>
    <img class="line" src="{% static 'img/Line 5.png' %}" alt="">
    {% endfor %}
    <div class="button">
        <a class="logout" href="{% url 'accounts:logout' %}">로그아웃</a>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'nav_bar.html' %}
{% block content %}
{% load static %}
<div class="container">
    <link rel="stylesheet" href="{% static 'css/signup.css' %}">
        <div class="nav-bar">
        </div>
            <img src="{% static 'img/image 55.png' %}" alt="" class="logo">
        <div class="input">
            <form action="" method="post" onsubmit="checkPassword()">
                {% csrf_token %}
                <!-- <p for="username">아이디</p> -->
                <input class="nickname" type="text" id="username" name="username" placeholder="ID" required>
                <p id="alert">아이디는 7자 이하로 적어주세요!</p> <!--경고 추가-->

                <!-- <p for="email">이메일</p> -->
                <input class="nickname" type="email" id="email" name="email" placeholder="email" required>

                <!-- <p for="password">비밀번호</p> -->
                <input class="nickname" type="password" id="password" name="password1" placeholder="password" required>

                <!-- <p for="password-confirm">비밀번호 확인</p> -->
                <input class="nickname" type="password" id="password-confirm" name="password2" placeholder="password check" required>
                <div class="button">
                    <button type="submit" onclick="return validateForm()" id="stop">Sign up</button>
                </div>
            </form>
        </div>
</div>
    <script src="{% static 'js/signup.js' %}"></script>
{% endblock %}