accounts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('my_page/<int:pk>/', views.my_page, name='my_page')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

boards/urls.py
from django.urls import path
from .views import *

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', main_page, name='main'),
    path('board/', board_list, name='board_list'),
    path('board/post/', board_post, name='board_post'),
    path('board/<int:pk>/', board_detail, name='board_detail'),
    path('board/update/<int:pk>/', board_update, name='board_update'),
    path('board/delete/<int:pk>/', board_delete, name='board_delete'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

petthon/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('boards.urls')),
]

templates/nav_bar.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>nav_bar</title>
    <link rel="stylesheet" href="{% static 'css/nav-bar.css' %}">
</head>
<body>
    <!--상단바 -->
    <div class="nav_bar">
        <div class="icons">
            <div class="back_icon">
                <img src="{% static 'img/_.png' %}" alt="" onclick="window.history.back()">
            </div>

            <div class="logo_icon">
                <a href="{% url 'main' %}"> <!--★★여기가 메인페이지 연결이래용-->
                    <img src="{% static 'img/image 54.png' %}" alt="">
                </a>
            </div>
            {% if user.is_authenticated %}
            <div class="login">
                <a href="{% url 'accounts:my_page' pk=user.pk %}">{{ user.username }} 님</a>
            </div>
            {% else %}
            <div class="login">
                <a href="{% url 'accounts:login' %}">로그인</a>
            </div>
            {% endif %}
        </div>
    </div>
    {% block content %}

    {% endblock %}
</body>
</html>

templates/post_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Petthon: 글 등록</title>
    <link rel="stylesheet" href="../static/css/post_create.css"> <!--{% static 'css/post_create.css' %}-->
</head>
<body>
    <div class="container">    
        <form name="writeText" class="editText" method="POST">
            
            <div class="pushBtn"> <!--등록 버튼-->
                <button type="submit" id="stop">등록</button>
            </div>

            
            <p id="alertText">제목을 작성해주세요!</p>

            <div>
                <p class="title">제목:</p> <!--제목 부분-->
                <textarea name="title" id="postTitle" rows="0" maxlength="17" oninput="maxLengthCheck(this)"
                placeholder="17자 이내로 제목을 입력해주세요."></textarea> 
            </div>
            
            <div>
                <p class="name">이름:</p> <!--반려동물 이름 부분-->
                <textarea name="title" id="name" rows="0" maxlength="17" oninput="maxLengthCheck(this)"
                placeholder="반려동물 이름을 알려주세요!"></textarea>
            </div>

            <div> 
                <p class="age">나이:</p> <!--반려동물 나이 부분-->
                <textarea name="title" id="age" rows="0" maxlength="2" oninput="maxLengthCheck(this)"
                placeholder="반려동물 나이를 알려주세요! (숫자만)"></textarea>
            </div>
            
            <p class="text">내용</p> <!--게시글 내용 부분-->
            <textarea name="edit" rows="0" id="editArea" maxlength="150" oninput="maxLengthCheck(this)"
            placeholder="반려동물 자랑을 적어주세요!&#10;&#10;ex)우리 집 고양이 귀엽죠?"></textarea>
            <div id="charCount">(0 / 150)</div> <!--글자수-->


            <div class="imageArea"> <!--업로드 한 사진 부분-->
                <p class="picture">사진</p>
                <p id="upload">사진을 업로드 해주세요!</p>
                <img src="" alt="" id = "change">
                <div id="del">&#215;</div>
            </div>

            <div class="image"> <!--사진 등록 부분-->
                <label for="fileInput" id="imageButton">
                    <img src="../static/img/camera.png" alt="파일 선택하기"> <!--{% static 'img/camera.png' %}-->
                </label>
                <input type="file" id="fileInput"> <!--파일 선택-->
                <span id="fileName"></span>
            </div>
        </form>

    <script src="../static/js/post_create.js"></script> <!--{% static 'js/post_create.js' %}-->
</body>
</html>

templates/signup.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="../static/css/signup.css">
</head>

<body>
    <div class="container">


        <div class="nav-bar">
        </div>
      
            <img src="../static/img/image 55.png" alt="" class="logo">
        
        <div class="input">
            <form action="" method="post" onsubmit="checkPassword()">
         
                <!-- <p for="username">아이디</p> -->
                <input class="nickname" type="text" id="username" name="username" placeholder="name" required>

                <!-- <p for="email">이메일</p> -->
                <input class="nickname" type="email" id="email" name="email" placeholder="email" required>

                <!-- <p for="password">비밀번호</p> -->
                <input class="nickname" type="password" id="password" name="password1" placeholder="password" required>

                <!-- <p for="password-confirm">비밀번호 확인</p> -->
                <input class="nickname" type="password" id="password-confirm" name="password2" placeholder="password check" required>
                <div class="button">
                    <button type="submit" onclick="return validateForm()">Sign up</button>
                </div>
            </form>
        </div>

    </div>







    <script src="../static/js/signup.js"></script>
</body>

</html>